const SUPABASE_URL='https://ftyvjlnrmvtptdbmwvug.supabase.co';
const SUPABASE_KEY='sb_publishable_6HysHTrRzTyXhZyE0Pph_g_kUuj-Bnk';
const ADMIN_UID='41ddb5ab-b16c-47d7-bf81-39196947ab29';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=id=>document.getElementById(id);
const fields=['data','serie','titulo','versiculo','meditacao','desafio','oracao','musica1','link_musica1','musica2','link_musica2','musica3','link_musica3'];
function msg(id,text,error=false){const e=$(id);e.textContent=text;e.classList.remove('hidden');e.style.background=error?'#fdecec':'#eef8f0'}
function showPanel(session){const ok=session?.user?.id===ADMIN_UID;$('login').classList.toggle('hidden',ok);$('panel').classList.toggle('hidden',!ok);if(ok)loadList();else if(session)msg('loginStatus','Este usuário não possui acesso administrativo.',true)}
async function login(){const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return msg('loginStatus',error.message,true);showPanel(data.session)}async function logout(){await sb.auth.signOut();showPanel(null)}
function payload(){const p={};fields.forEach(k=>p[k]=$(k).value.trim());return p}
function clearForm(){['editId',...fields.filter(k=>k!=='serie')].forEach(x=>$(x).value='');$('serie').value='presenca';$('formTitle').textContent='Nova meditação';$('cancelBtn').classList.add('hidden')}
async function save(){const p=payload();if(!p.data||!p.titulo||!p.versiculo||!p.meditacao)return msg('formStatus','Preencha data, título, versículo e meditação.',true);const id=$('editId').value;const q=id?sb.from('meditacoes').update(p).eq('id',id):sb.from('meditacoes').insert(p);const {error}=await q;if(error)return msg('formStatus',error.message,true);msg('formStatus',id?'Meditação atualizada com sucesso.':'Meditação cadastrada com sucesso.');clearForm();loadList()}
async function loadList(){const {data,error}=await sb.from('meditacoes').select('*').order('data',{ascending:false});if(error){$('list').textContent=error.message;return}$('list').innerHTML=data.length?'':'Nenhuma meditação cadastrada no banco ainda.';data.forEach(r=>{const d=document.createElement('div');d.className='item';const t=document.createElement('strong');t.textContent=`${r.data} — ${r.titulo}`;d.append(t,document.createElement('br'));const e=document.createElement('button');e.textContent='Editar';e.onclick=()=>edit(r);const dup=document.createElement('button');dup.textContent='Duplicar';dup.onclick=()=>duplicate(r);const del=document.createElement('button');del.textContent='Excluir';del.className='danger';del.onclick=()=>removeRow(r.id,r.titulo);d.append(e,dup,del);$('list').appendChild(d)})}
function fill(r,duplicate=false){$('editId').value=duplicate?'':r.id;fields.forEach(k=>$(k).value=r[k]||'');if(duplicate)$('data').value='';$('formTitle').textContent=duplicate?'Duplicar meditação':'Editar meditação';$('cancelBtn').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}function edit(r){fill(r)}function duplicate(r){fill(r,true)}
async function removeRow(id,title){if(!confirm(`Excluir “${title}”?`))return;const {error}=await sb.from('meditacoes').delete().eq('id',id);if(error)return alert(error.message);loadList()}
$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('saveBtn').onclick=save;$('cancelBtn').onclick=clearForm;sb.auth.getSession().then(({data})=>showPanel(data.session));